### PR TITLE
Switch to node10 alpine base image

### PR DESCRIPTION
**Pull request by mroote**
Switched the base image to use the alpine node image.

Versions installed:
```
$ docker run -ti gitlab-ci-dockerjs /bin/sh
/ # node --version
v10.18.1
/ # yarn --version
1.21.1
```

### CODE REVIEW

**Comment by RouganStriker** [comment]
I wonder if we can use the same image for all the runners instead. Else this seems fine if it works

**Comment by mroote** [comment]
Yeah I'm not sure exactly why this container was created instead of reusing the existing gitlab-runner container. Maybe @emintham knows?

**Comment by emintham** [comment]
Not sure :/ ask Adam...

**Comment by funkaoshi** [comment]
Can we merge this and then decide? I'm not sure if we wanted a runner that didn't have all the Python junk?

**Pull request merged**
