### PR TITLE
Install and configure git-lfs into container

### PR DESCRIPTION
**Pull request by hrpatel**

### CODE REVIEW

**Comment by hrpatel** [comment]
@RouganStriker You OK to make this into a new container on Docker hub? 
FYI @MichelleFuncke

**Comment by mroote** [comment]
I think the container will auto rebuild. I can see it launched a job to build a container from this branch already: https://hub.docker.com/repository/registry-1.docker.io/sdelements/gitlab-ci-dockerjs-runner/builds/686b73ec-3e31-457c-8a44-d4884f0c1b3f.

**Comment by mroote** [comment]
+1

**Comment by RouganStriker** [comment]
+1 if it works =P

**Comment by mroote** [comment]
Good to merge? it will rebuild the `latest` tagged container when merged into master.

**Pull request merged**
